const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 5.0,
      numReviews: 131,
      description: "Cristiano Ronaldo daily shirt",
    },
    {
        name: "Adidas Slim shirt",
        slug: "adidas-slim-shirt",
        category: "Shirts",
        image: "/images/p2.jpg",
        price: 115,
        countInStock: 15,
        brand: "Adidas",
        rating: 4.7,
        numReviews: 129,
        description: "Leo Messi daily shirt",
      },
      {
        name: "Nike Slim Pant",
        slug: "nike-slim-pant",
        category: "Pants",
        image: "/images/p3.jpg",
        price: 100,
        countInStock: 11,
        brand: "Nike",
        rating: 4.6,
        numReviews: 97,
        description: "Cristiano Ronaldo daily pants",
      },
      {
        name: "Puma Slim Pant",
        slug: "puma-slim-pant",
        category: "Pants",
        image: "/images/p4.jpg",
        price: 110,
        countInStock: 21,
        brand: "Puma",
        rating: 4.8,
        numReviews: 88,
        description: "Alexis Sanchez daily pants",
      },
  ],
};

export default data;
